"
" my .vimrc
" 

"Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

set incsearch
set tabstop=4
set shiftwidth=4
set expandtab

"set cmdheight=3
set ruler
"set path=PATH1,PATH2,...


filetype plugin on
colorscheme evening

autocmd BufNewFile,BufRead *[.h|.c] set formatprg=astyle
map <S-F> <Esc>:%! astyle<CR>
nmap <F6> :TListToggle<CR>

source $VIMRUNTIME/ftplugin/man.vim


" 自动识别文件的编码格式
set fileencodings=GBK,UTF-8,gb18030,ucs-bom,cp936
" 标识源文件中的数据的内码格式
set fileencoding=GBK
" 标识vim buffer中的数据编码格式
set encoding=UTF-8

set cscopequickfix=s-,c-,d-,i-,t-,e-"
set splitright "for cscope vert scs

